# Generated by Django 5.0.6 on 2024-06-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField()),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FeriaCiencias.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FeriaCiencias.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='idSeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FeriaCiencias.seccion'),
        ),
    ]
