# Generated by Django 4.2.13 on 2024-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeriaCiencias', '0002_rename_nombre_articulo_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimagen',
            name='imagen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.CharField(max_length=50),
        ),
    ]
