# Generated by Django 4.2.13 on 2024-07-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeriaCiencias', '0003_alter_artimagen_imagen_alter_proyecto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='link',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seccion',
            name='link',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
